# Generated by Django 5.2.17 on 2026-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('nearby', 'Yakınınızda'), ('popular', 'Popüler oluyor')], default='nearby', max_length=20),
        ),
    ]
