# Generated by Django 5.2.17 on 2026-08-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_home_location_user_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('municipality', 'Belediye'), ('institution', 'Kurum / Topluluk')], max_length=20),
        ),
    ]
