// next-env.d.ts carries this same reference, but it's generated by `next dev`/`next
// build` and gitignored — CI runs `tsc --noEmit` on a fresh checkout where it doesn't
// exist yet, so the image-import types (used for the Leaflet marker icons) need a
// committed source too.
/// <reference types="next/image-types/global" />
