# Generated by Django 5.2.17 on 2026-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('rejected', 'Reddedildi')], default='open', max_length=20),
        ),
    ]
