# Generated by Django 5.2.17 on 2026-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('issue', 'Sorun / Şikayet'), ('request', 'Talep'), ('announcement', 'Duyuru'), ('event', 'Etkinlik')], default='issue', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='visibility',
            field=models.CharField(choices=[('public', 'Herkese açık'), ('members', 'Yalnızca üyelere')], default='public', max_length=20),
        ),
    ]
