# Generated by Django 5.2.17 on 2026-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_type_report_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='reports/thumbs/%Y/%m/'),
        ),
    ]
