# Generated by Django 5.2.17 on 2026-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_event_ends_at_report_event_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='popular_notified',
            field=models.BooleanField(default=False),
        ),
    ]
